---
title: "My dashboard "
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

```{r}
data("instacart")

```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>%
  group_by(aisle) %>%
  summarize(count = n()) %>% 
  filter(count >= 10000) %>%  #more than 10000 items ordered
  plot_ly(x = ~ reorder(aisle,desc(count)), y = ~count, color = ~aisle ,type = "bar") %>% 
  layout(
    title = "The Number of Items Ordered in Each Aisle",
    xaxis = list(title = "Each aisle"),
    yaxis = list(title = "Count")
    )

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>%
  filter(department %in% c("produce","bakery","dairy eggs","beverages","pantry")) %>% 
  group_by(order_hour_of_day,department) %>%
  summarise(
    count = n()
    ) %>% 
  plot_ly(
  x = ~order_hour_of_day, y = ~count, color = ~department, type = "scatter", mode = "line"
  ) %>% 
  layout(
    title = "Order Hour of Day of Different Department",
    xaxis = list(title = "Order Hour of Day"),
    yaxis = list(title = "Count")
    )

```

### Chart C

```{r}
instacart %>%
  filter(department == "bakery") %>% 
  plot_ly(
  x = ~aisle, y = ~order_hour_of_day, type = "box", color = ~aisle
  ) %>% 
  layout(
    title = "Order Hour of Day for Bakery Department",
    xaxis = list(title = "Aisle of bakery"),
    yaxis = list(title = "Order hour of day")
    )

```


